import "./globals.css";

import { Chakra_Petch } from "next/font/google";
import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";

const chakra = Chakra_Petch({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chakra.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
